Install referenced schema in "npm:validate" task
The "npm:validate" task validates the repository's `package.json` npm manifest file against its JSON schema to catch any
problems with its data format.

In order to avoid duplication of content, JSON schemas may reference other schemas via the `$ref` keyword. The
`package.json` schema was recently updated to share resources with several other schemas, which caused the validation to
start failing:

schema /tmp/package-json-schema-3RnDtCIiPG.json is invalid
error: can't resolve reference https://json.schemastore.org/partial-eslint-plugins.json from id https://json.schemastore.org/eslintrc.json#

The solution is to configure the task to download the referenced schemas and provide their paths to the avj-cli
validator via `-r` flags.